server:
  port: 8888

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/stock?useUnicode=true&characterEncoding=utf-8&useSSL=true&useTimezone=true&serverTimezone=GMT%2B8&rewriteBatchedStatements=true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.example.entity
  config-location: classpath:config/mybatis-config.xml

logging:
  level:
    com.baomidou.mybatisplus.samples: debug
